version: "3.1"

services:
    db:
        image: postgres:13-alpine
        container_name: blit-blog-postgres
        ports:
            - "5432:5432"
        restart: always
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: password
            POSTGRES_DB: testdb
        volumes:
            - dbdata:/var/lib/postgresql/data
    blog:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "30000:3000"
        volumes:
            - ./blog:/usr/src
        command: /bin/sh -c "cd /usr/src/blitz-blog && blitz start"
        depends_on:
            - db
volumes:
    dbdata: